import React, { useState } from "react";
import { Bar, Doughnut } from "react-chartjs-2";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  ArcElement,
  Tooltip,
  Legend
} from "chart.js";
import jsPDF from "jspdf";
import styles from "./Dashboard.module.css";

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  ArcElement,
  Tooltip,
  Legend
);

const initialData = {
  profile: {
    name: "John Doe",
    email: "john@example.com",
    role: "AI Productivity User",
    avatar: "https://i.pravatar.cc/100"
  },

  status: {
    tracking: false,
    trackerOffTime: "1h 15m",
    lastActive: "2026-01-10T09:45:00Z",
    currentTask: "Idle"
  },

  productivity: {
    score: 72,
    totalTime: "7h 10m",
    productiveTime: "4h 30m",
    wastedTime: "1h 25m"
  },

  apps: [
    { name: "VS Code", time: 130, openCount: 5, type: "Productive" },
    { name: "Chrome", time: 100, openCount: 12, type: "Neutral" },
    { name: "YouTube", time: 70, openCount: 8, type: "Unproductive" }
  ],

  weeklySummary: [
    { day: "Mon", productive: 200, wasted: 90, score: 70 },
    { day: "Tue", productive: 250, wasted: 80, score: 78 },
    { day: "Wed", productive: 230, wasted: 110, score: 72 },
    { day: "Thu", productive: 240, wasted: 100, score: 75 },
    { day: "Fri", productive: 260, wasted: 90, score: 80 }
  ]
};

const Dashboard = () => {
  const [data, setData] = useState(initialData);

  const handleStartTracking = () => {
    console.log("Tracking Started");
    setData(prev => ({
      ...prev,
      status: { ...prev.status, tracking: true, currentTask: "Coding" }
    }));
  };

  const handleEditProfile = () => {
    console.log("Edit Profile Clicked");
  };

const downloadWeeklyReport = () => {
  const doc = new jsPDF();

  /* ====== TITLE ====== */
  doc.setFontSize(20);
  doc.setTextColor(59, 130, 246); // blue
  doc.text("AI Weekly Productivity Report", 14, 20);

  doc.setFontSize(11);
  doc.setTextColor(150);
  doc.text("Generated by ScreenSense AI", 14, 28);

  /* ====== TABLE HEADER ====== */
  const startY = 40;
  let y = startY;

  doc.setFillColor(18, 24, 38); // dark header bg
  doc.rect(14, y, 182, 10, "F");

  doc.setTextColor(255);
  doc.setFontSize(12);
  doc.text("Day", 20, y + 7);
  doc.text("Productive (min)", 55, y + 7);
  doc.text("Wasted (min)", 105, y + 7);
  doc.text("Score (%)", 150, y + 7);

  y += 10;

  /* ====== TABLE ROWS ====== */
  data.weeklySummary.forEach((day, index) => {
    // Alternate row color
    if (index % 2 === 0) {
      doc.setFillColor(245, 247, 250);
      doc.rect(14, y, 182, 10, "F");
    }

    doc.setTextColor(40);
    doc.text(day.day, 20, y + 7);
    doc.text(`${day.productive}`, 65, y + 7);
    doc.text(`${day.wasted}`, 115, y + 7);
    doc.text(`${day.score}%`, 155, y + 7);

    y += 10;
  });

  /* ====== BORDER ====== */
  doc.setDrawColor(200);
  doc.rect(14, startY, 182, y - startY);

  /* ====== FOOTER ====== */
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(
    "AI-based productivity insights • ScreenSense AI",
    14,
    285
  );

  doc.save("Weekly_Productivity_Report.pdf");
};


  const weeklyChart = {
    labels: data.weeklySummary.map(d => d.day),
    datasets: [
      {
        label: "Productive Time",
        data: data.weeklySummary.map(d => d.productive),
        backgroundColor: "#3B82F6"
      },
      {
        label: "Wasted Time",
        data: data.weeklySummary.map(d => d.wasted),
        backgroundColor: "#EF4444"
      }
    ]
  };

  const appChart = {
    labels: data.apps.map(a => a.name),
    datasets: [
      {
        data: data.apps.map(a => a.time),
        backgroundColor: ["#3B82F6", "#8B5CF6", "#22D3EE"]
      }
    ]
  };

  return (
    <div className={styles.container}>
      <h1 className={styles.title}>AI Productivity Dashboard</h1>

      {/* PROFILE */}
      <div className={styles.profileCard}>
        <img src={data.profile.avatar} alt="profile" />
        <div>
          <h3>{data.profile.name}</h3>
          <p>{data.profile.email}</p>
          <span>{data.profile.role}</span>
        </div>
        <button className={styles.editBtn} onClick={handleEditProfile}>
          ✏️
        </button>
      </div>

      {/* STATUS */}
      <div className={styles.card}>
        <p>Status: <span>{data.status.tracking ? "Tracking" : "Idle"}</span></p>
        <p>Current Task: {data.status.currentTask}</p>
        <p>Tracker OFF Time: {data.status.trackerOffTime}</p>
        <p>Last Active: {new Date(data.status.lastActive).toLocaleTimeString()}</p>
      </div>

      {/* PRODUCTIVITY */}
      <div className={styles.card}>
        <h3>Productivity Score: {data.productivity.score}%</h3>
        <div className={styles.progressBar}>
          <div style={{ width: `${data.productivity.score}%` }} />
        </div>
        <p>Total: {data.productivity.totalTime}</p>
        <p>Productive: {data.productivity.productiveTime}</p>
        <p>Wasted: {data.productivity.wastedTime}</p>
      </div>

      {/* CHARTS */}
      <div className={styles.charts}>
        <div className={styles.chartCard}>
          <h4>Weekly Productivity</h4>
          <Bar data={weeklyChart} />
        </div>

        <div className={styles.chartCard}>
          <h4>App Usage</h4>
          <Doughnut data={appChart} />
        </div>
      </div>

      {/* APPS TABLE */}
      <div className={styles.card}>
        <h3>Application Usage</h3>
        <table>
          <thead>
            <tr>
              <th>App</th>
              <th>Usage (min)</th>
              <th>Open Count</th>
              <th>Type</th>
            </tr>
          </thead>
          <tbody>
            {data.apps.map((app, i) => (
              <tr key={i}>
                <td>{app.name}</td>
                <td>{app.time}</td>
                <td>{app.openCount}</td>
                <td>{app.type}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <button className={styles.startButton} onClick={handleStartTracking}>
        Start Tracking
      </button>

      <button className={styles.downloadBtn} onClick={downloadWeeklyReport}>
        Download Weekly Report (PDF)
      </button>
    </div>
  );
};

export default Dashboard;
