import React, { useState } from "react";
import { Bar, Doughnut } from "react-chartjs-2";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  ArcElement,
  Tooltip,
  Legend,
} from "chart.js";
import jsPDF from "jspdf";
import styles from "./Dashboard.module.css";
import { Navigate, useNavigate } from "react-router-dom";

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  ArcElement,
  Tooltip,
  Legend
);

const initialData = {
  profile: {
    name: "John Doe",
    email: "john@example.com",
    role: "AI Productivity User",
    avatar: "https://i.pravatar.cc/100",
  },

  status: {
    tracking: false,
    trackerOffTime: "1h 15m",
    lastActive: "2026-01-10T09:45:00Z",
    currentTask: "Idle",
  },

  productivity: {
    score: 72,
    totalTime: "7h 10m",
    productiveTime: "4h 30m",
    wastedTime: "1h 25m",
  },

  apps: [
    { name: "YouTube", time: 70, openCount: 8, type: "Unproductive" },
    { name: "Chrome", time: 100, openCount: 12, type: "Neutral" },
    { name: "YouTube", time: 70, openCount: 8, type: "Unproductive" },
  ],

  weeklySummary: [
    { day: "Mon", productive: 200, wasted: 90, score: 70 },
    { day: "Tue", productive: 250, wasted: 80, score: 78 },
    { day: "Wed", productive: 230, wasted: 110, score: 72 },
    { day: "Thu", productive: 240, wasted: 100, score: 75 },
    { day: "Fri", productive: 260, wasted: 90, score: 80 },
  ],
};

const Dashboard = () => {
  const [data, setData] = useState(initialData);
  const navigate = useNavigate();
  const handleStartTracking = () => {
    console.log("Tracking Started");
    setData((prev) => ({
      ...prev,
      status: { ...prev.status, tracking: true, currentTask: "Coding" },
    }));
  };
  const toggleTracking = async () => {
    const isTracking = data.status.tracking;
const userId = localStorage.getItem('userId');
    const endpoint = isTracking
      ? "https://unslayable-unfelicitous-karl.ngrok-free.dev/api/tracking/disable"
      : "https://unslayable-unfelicitous-karl.ngrok-free.dev/api/tracking/enable";

    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
          "ngrok-skip-browser-warning": "true",
        },
        body: JSON.stringify({
          userId: 1,
        }),
      });

      const result = await response.json();
      console.log("Tracking response:", result);

      // ✅ Update UI state after API success
      setData((prev) => ({
        ...prev,
        status: {
          ...prev.status,
          tracking: !isTracking,
          currentTask: !isTracking ? "Tracking Active" : "Idle",
        },
      }));
    } catch (error) {
      console.error("Tracking toggle error:", error);
    }
  };

  const handleEditProfile = () => {
    navigate("/profile");
  };

  const downloadWeeklyReport = () => {
    const doc = new jsPDF();

    /* ====== TITLE ====== */
    doc.setFontSize(20);
    doc.setTextColor(59, 130, 246); // blue
    doc.text("AI Weekly Productivity Report", 14, 20);

    doc.setFontSize(11);
    doc.setTextColor(150);
    doc.text("Generated by ScreenSense AI", 14, 28);

    /* ====== TABLE HEADER ====== */
    const startY = 40;
    let y = startY;

    doc.setFillColor(18, 24, 38); // dark header bg
    doc.rect(14, y, 182, 10, "F");

    doc.setTextColor(255);
    doc.setFontSize(12);
    doc.text("Day", 20, y + 7);
    doc.text("Productive (min)", 55, y + 7);
    doc.text("Wasted (min)", 105, y + 7);
    doc.text("Score (%)", 150, y + 7);

    y += 10;

    /* ====== TABLE ROWS ====== */
    data.weeklySummary.forEach((day, index) => {
      // Alternate row color
      if (index % 2 === 0) {
        doc.setFillColor(245, 247, 250);
        doc.rect(14, y, 182, 10, "F");
      }

      doc.setTextColor(40);
      doc.text(day.day, 20, y + 7);
      doc.text(`${day.productive}`, 65, y + 7);
      doc.text(`${day.wasted}`, 115, y + 7);
      doc.text(`${day.score}%`, 155, y + 7);

      y += 10;
    });

    /* ====== BORDER ====== */
    doc.setDrawColor(200);
    doc.rect(14, startY, 182, y - startY);

    /* ====== FOOTER ====== */
    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text("AI-based productivity insights • ScreenSense AI", 14, 285);

    doc.save("Weekly_Productivity_Report.pdf");
  };

  const weeklyChart = {
    labels: data.weeklySummary.map((d) => d.day),
    datasets: [
      {
        label: "Productive Time",
        data: data.weeklySummary.map((d) => d.productive),
        backgroundColor: "#3B82F6",
        borderRadius: 8,
        borderSkipped: false,
      },
      {
        label: "Wasted Time",
        data: data.weeklySummary.map((d) => d.wasted),
        backgroundColor: "#EF4444",
        borderRadius: 8,
        borderSkipped: false,
      },
    ],
  };

  const appChart = {
    labels: data.apps.map((a) => a.name),
    datasets: [
      {
        data: data.apps.map((a) => a.time),
        backgroundColor: ["#3B82F6", "#8B5CF6", "#22D3EE"],
        borderWidth: 0,
      },
    ],
  };

  const chartOptions = {
    responsive: true,
    maintainAspectRatio: true,
    plugins: {
      legend: {
        labels: {
          color: "#9CA3AF",
          font: { size: 12 },
        },
      },
    },
    scales: {
      y: {
        grid: { color: "rgba(255,255,255,0.05)" },
        ticks: { color: "#9CA3AF" },
      },
      x: {
        grid: { color: "rgba(255,255,255,0.05)" },
        ticks: { color: "#9CA3AF" },
      },
    },
  };

  const doughnutOptions = {
    responsive: true,
    maintainAspectRatio: true,
    plugins: {
      legend: {
        position: "bottom",
        labels: {
          color: "#9CA3AF",
          font: { size: 12 },
          padding: 15,
        },
      },
    },
  };

  return (
    <div className={styles.container}>
      {/* Background Effects */}
      <div className={styles.bgParticles}>
        <div className={styles.particle1}></div>
        <div className={styles.particle2}></div>
        <div className={styles.particle3}></div>
      </div>

      <div className={styles.scanLine}></div>

      {/* Header */}
      <div className={styles.header}>
        <div className={styles.headerLeft}>
          <div className={styles.logoIcon}>
            <svg viewBox="0 0 24 24" fill="none">
              <path
                d="M12 2L2 7L12 12L22 7L12 2Z"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M2 17L12 22L22 17"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M2 12L12 17L22 12"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </div>
          <div>
            <h1 className={styles.title}>AI Productivity Dashboard</h1>
            <p className={styles.subtitle}>Neural Analytics Engine v4.2</p>
          </div>
        </div>

        <div className={styles.statusBadge}>
          <span className={styles.statusDot}></span>
          System Active
        </div>
      </div>

      {/* Profile Card */}
      <div className={styles.profileCard}>
        <div className={styles.profileLeft}>
          <div className={styles.avatarWrapper}>
            <img src={data.profile.avatar} alt="profile" />
            <div className={styles.avatarGlow}></div>
          </div>
          <div className={styles.profileInfo}>
            <h3>{data.profile.name}</h3>
            <p>{data.profile.email}</p>
            <span className={styles.roleBadge}>
              <span className={styles.roleIcon}>🤖</span>
              {data.profile.role}
            </span>
          </div>
        </div>
        <button className={styles.editBtn} onClick={handleEditProfile}>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
            <path
              d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
            <path
              d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        </button>
      </div>

      {/* Grid Layout */}
      <div className={styles.grid}>
        {/* Status Card */}
        <div className={styles.card}>
          <div className={styles.cardHeader}>
            <h3>System Status</h3>
            <div className={styles.liveBadge}>
              <span className={styles.liveDot}></span>
              Live
            </div>
          </div>
          <div className={styles.statusGrid}>
            <div className={styles.statusItem}>
              <span className={styles.statusLabel}>Status</span>
              <span
                className={`${styles.statusValue} ${
                  data.status.tracking ? styles.active : styles.idle
                }`}
              >
                {data.status.tracking ? "🟢 Tracking" : "⚪ Idle"}
              </span>
            </div>
            <div className={styles.statusItem}>
              <span className={styles.statusLabel}>Current Task</span>
              <span className={styles.statusValue}>
                {data.status.currentTask}
              </span>
            </div>
            <div className={styles.statusItem}>
              <span className={styles.statusLabel}>Tracker OFF Time</span>
              <span className={styles.statusValue}>
                {data.status.trackerOffTime}
              </span>
            </div>
            <div className={styles.statusItem}>
              <span className={styles.statusLabel}>Last Active</span>
              <span className={styles.statusValue}>
                {new Date(data.status.lastActive).toLocaleTimeString()}
              </span>
            </div>
          </div>
        </div>

        {/* Productivity Score */}
        <div className={styles.card}>
          <div className={styles.cardHeader}>
            <h3>Productivity Score</h3>
            <span className={styles.scoreNumber}>
              {data.productivity.score}%
            </span>
          </div>
          <div className={styles.progressWrapper}>
            <div className={styles.progressBar}>
              <div
                className={styles.progressFill}
                style={{ width: `${data.productivity.score}%` }}
              >
                <div className={styles.progressGlow}></div>
              </div>
            </div>
          </div>
          <div className={styles.statsGrid}>
            <div className={styles.statItem}>
              <div className={styles.statIcon}>⏱️</div>
              <div>
                <p className={styles.statLabel}>Total Time</p>
                <p className={styles.statValue}>
                  {data.productivity.totalTime}
                </p>
              </div>
            </div>
            <div className={styles.statItem}>
              <div className={styles.statIcon}>✅</div>
              <div>
                <p className={styles.statLabel}>Productive</p>
                <p className={styles.statValue}>
                  {data.productivity.productiveTime}
                </p>
              </div>
            </div>
            <div className={styles.statItem}>
              <div className={styles.statIcon}>⚠️</div>
              <div>
                <p className={styles.statLabel}>Wasted</p>
                <p className={styles.statValue}>
                  {data.productivity.wastedTime}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Charts Section */}
      <div className={styles.chartsSection}>
        <div className={styles.chartCard}>
          <div className={styles.cardHeader}>
            <h3>Weekly Productivity Analysis</h3>
            <div className={styles.chartBadge}>📊 Chart View</div>
          </div>
          <div className={styles.chartWrapper}>
            <Bar data={weeklyChart} options={chartOptions} />
          </div>
        </div>

        <div className={styles.chartCard}>
          <div className={styles.cardHeader}>
            <h3>Application Usage</h3>
            <div className={styles.chartBadge}>🎯 Distribution</div>
          </div>
          <div className={styles.chartWrapper}>
            <Doughnut data={appChart} options={doughnutOptions} />
          </div>
        </div>
      </div>

      {/* Apps Table */}
      <div className={styles.card}>
        <div className={styles.cardHeader}>
          <h3>Application Activity Log</h3>
          <div className={styles.tableBadge}>
            {data.apps.length} Applications
          </div>
        </div>
        <div className={styles.tableWrapper}>
          <table className={styles.table}>
            <thead>
              <tr>
                <th>Application</th>
                <th>Usage Time</th>
                <th>Open Count</th>
                <th>Category</th>
              </tr>
            </thead>
            <tbody>
              {data.apps.map((app, i) => (
                <tr key={i}>
                  <td>
                    <div className={styles.appName}>
                      <span className={styles.appIcon}>📱</span>
                      {app.name}
                    </div>
                  </td>
                  <td>{app.time} min</td>
                  <td>{app.openCount}x</td>
                  <td>
                    <span
                      className={`${styles.typeBadge} ${
                        app.type === "Productive"
                          ? styles.productive
                          : app.type === "Neutral"
                          ? styles.neutral
                          : styles.unproductive
                      }`}
                    >
                      {app.type}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Action Buttons */}
      <div className={styles.actionButtons}>
        <button className={styles.startButton} onClick={toggleTracking}>
          <span className={styles.buttonIcon}>
            {data.status.tracking ? "⏹️" : "▶️"}
          </span>
          <span>
            {data.status.tracking ? "Stop AI Tracking" : "Start AI Tracking"}
          </span>
          <div className={styles.buttonGlow}></div>
        </button>

        <button className={styles.downloadBtn} onClick={downloadWeeklyReport}>
          <span className={styles.buttonIcon}>📥</span>
          <span>Download Weekly Report</span>
          <div className={styles.buttonGlow}></div>
        </button>
      </div>

      {/* AI Processing Indicator */}
      <div className={styles.footer}>
        <div className={styles.processingIndicator}>
          <div className={styles.processingDot}></div>
          <div className={styles.processingDot}></div>
          <div className={styles.processingDot}></div>
        </div>
        <p className={styles.footerText}>
          Powered by Advanced AI Neural Network • Real-time Analytics
        </p>
      </div>
    </div>
  );
};

export default Dashboard;
